version: '3'

services:
  externalstructureproxy-web:
    build: .
    volumes:
      - ./output:/output:rw
      - ./data:/app/data:ro
      - ./ftpproxy:/ftpproxy:rw
    ports:
      - "5010:5000"
    command: /app/run_server.sh

  externalstructureproxy-beat1:
    build: .
    container_name: externalstructureproxy-beat1
    volumes:
        - ./output:/output:rw
    networks:
      - default
    restart: unless-stopped
    command: /app/run_beat.sh
    depends_on: 
      - externalstructureproxy-rabbitmq

  externalstructureproxy-worker1:
    build: .
    container_name: externalstructureproxy-worker1
    volumes:
        - ./output:/output:rw
    networks:
      - default
    restart: unless-stopped
    command: /app/run_worker.sh
    depends_on: 
      - externalstructureproxy-rabbitmq

  externalstructureproxy-rabbitmq:
    image: rabbitmq:latest
    networks:
      - default

  externalstructureproxy-redis:
    image: redis:latest
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - default
    command: redis-server /usr/local/etc/redis/redis.conf

networks:
  nginx-net:
    external:
      name: nginx-net