version: '3'

services:
  externalstructureproxy-web:
    networks:
      - default
      - nginx-net
    environment:
      VIRTUAL_HOST: external.gnps2.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: external.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com
    command: /app/run_production_server.sh

  externalstructureproxy-library_generation_worker:
    volumes:
        - /data/gscratch/:/data/gscratch:rw
  
  externalstructureproxy-library_harmonization_worker:
    volumes:
        - /data/gscratch/:/data/gscratch:rw
  
  externalstructureproxy-api_request_worker:
    volumes:
        - /data/gscratch/:/data/gscratch:rw

  externalstructureproxy-library_api_retrieve_worker:
    volumes:
        - /data/gscratch/:/data/gscratch:rw
    
networks:
  nginx-net:
    external:
      name: nginx-net