name: production-integration

on: 
  push:
  schedule:
   - cron:  '15 * * * *'

jobs:
  production-integration:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10.16
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.16
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pandas
    - name: Test with pytest
      run: |
        pip install nose2
        cd test-production-integration	&& nose2 -v
